#!/usr/bin/env python3

import argparse
import socket


def main():
    ap = argparse.ArgumentParser("Fileget")

    ap.add_argument("-n", required=True)
    ap.add_argument("-f", required=True)

    args = ap.parse_args()

    print("file:\t\t" + args.f)
    print("namespace:\t" + args.n)

    # try:

    fileserver = ""

    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
        s.connect(('127.0.0.2', 42069))
        s.sendall(b'WHEREIS file.server.two')
        data = s.recv(1024).decode()
        print(data)

        if (data.split(' ')[0] == 'OK'):
            print("success")
            fileserver = data.split(' ')[1]

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.connect((fileserver.split(":")[0], int(fileserver.split(':')[1])))
        mesg = "GET file FSP/1.0\r\nHostname: {file}\r\nAgent: xgysel00\r\n\r\n".format(
            file="file")
        s.sendall(mesg.encode())

        while True:
            data = s.recv(1024*2).decode()
            if data == "":
                break
            print(data)


if __name__ == "__main__":
    main()
