#!/usr/bin/env python3

import argparse
import socket
import logging as log
import re
import pathlib as path
from urllib.parse import urlparse
import sys


def parseAddress(addr):
    log.info("Parsing address " + addr)
    addr = addr.split(':')
    return (addr[0], int(addr[1]))


def getAddress(addr, file_server):
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
            msg = "WHEREIS {}".format(file_server.netloc).encode()

            log.info("Connecting to server " + addr.path)

            s.connect(parseAddress(addr.path))

            log.info("Sending request to server " + str(addr.path))
            s.send(msg)

            log.info("Receiving data from server " + str(addr.path))
            data = s.recv(1024).decode()
            # todo: space not required
            data = data.split(" ")
            if data[0] != 'OK':
                log.error("Response from server " +
                          str(addr.path) + " not OK")
                exit(1)
            log.info("Response OK")
            s.close()
            return urlparse(data[1])
    except:
        log.error("Something went wrong")
        exit(1)


def getFile(addr, surl):
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:

            log.info("Connecting to server " + addr.path)
            s.connect(parseAddress(addr.path))
            mesg = "GET {file} FSP/1.0\r\nHostname: {fileserver}\r\nAgent: xgysel00\r\n\r\n".format(
                file=re.sub(r'^\/', '', surl.path), fileserver=surl.netloc)

            log.info("Sending request to server " + addr.path)
            s.send(mesg.encode())

            file = b""
            while True:
                log.info("Receiving data from server " + addr.path)
                data = s.recv(1024)
                # print(data)
                if len(data) == 0:
                    break
                file = b''.join([file, data])
            s.close()
            # print(file, end='\n\n', )
            return file
    except:
        print()
        print(sys.exc_info())
        log.error("Something went wrong getting file")
        exit(1)


def checkFile(file):
    regex = br"^FSP\/1\.0 Success\r\nLength:\d+(\r\n){1,2}"

    head = re.search(regex, file)
    # print(head)
    if head == None:
        log.error("Something went wrong (no head)")
        print(file.decode())
        exit(1)
    file = re.sub(regex, b"", file)

    lenght = int(head.group().split(b'\r\n')[1].split(b':')[-1])
    if lenght != len(file):
        log.error("Something went wrong downloading file")
        exit(1)
    return file


def copyFile(filename, file):
    file = checkFile(file=file)

    try:
        # print(filename)
        filepath = filename.split('/')
        filename = filepath[-1]
        filepath = "/".join(filepath[1:-1])
        # print(filepath)

        path.Path(filepath).mkdir(parents=True, exist_ok=True)
        data_folder = path.Path(filepath)

        log.info("Opening file " + filename + " in directory " + filepath)
        f = open(data_folder / filename, "wb")
        f.write(file)
        f.close

    except:
        log.error("Something went wrong writing to file")
        exit(1)
    log.info("Copying finished")


def main():

    log.basicConfig(level=log.INFO)

    # parse program arguments
    ap = argparse.ArgumentParser("Fileget")
    ap.add_argument("-n", required=True)
    ap.add_argument("-f", required=True)

    log.info("Parsing program arguments")
    args = ap.parse_args()

    # get nameserver address
    nameserver = getAddress(
        addr=urlparse(args.n),
        file_server=urlparse(args.f)
    )

    # get file content
    surl = urlparse(args.f)

    # get file OR get all?

    if surl.path == '/*':
        surl = urlparse(re.sub(r'\*$', 'index', args.f))
        index = getFile(addr=nameserver, surl=surl)
        index = checkFile(file=index)

        fileList = index.decode().split('\r\n')
        fileList.remove('')
        print(fileList)

        for file in fileList:
            surl = urlparse(re.sub(r'\*$', file, args.f))
            print(surl.path)
            fileContent = getFile(addr=nameserver, surl=surl)
            copyFile(surl.path, fileContent)

    file = getFile(addr=nameserver, surl=surl)
    copyFile(surl.path, file)


if __name__ == "__main__":
    main()
